

server:
  port: ${APP_PORT:8090}
  servlet:
    context-path: /basket/api
    
    
management:
  health:
    show-details: always
  metrics:
    enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics
        
       